#!/bin/bash
set -e

echo "Starting Smart Mechanical Workshop Survey Web..."

# Default API URL if not provided
API_URL=${API_URL:-"/api/survey"}

echo "Configuring application with API_URL: $API_URL"

# Generate env-config.js with environment variables
cat > /usr/share/nginx/html/env-config.js <<EOF
// This file is auto-generated by docker-entrypoint.sh
// Do not edit manually
window.ENV_CONFIG = {
    API_URL: '${API_URL}'
};
EOF

echo "Environment configuration created successfully"

# Execute the CMD
exec "$@"
